let beautyData = [
  {
    department: "beauty & grooming",
    category: "bath,body & hygiene",
    img: "https://bit.ly/3EV3w7v",
    brand: "pears",
    name: "Pears Pure & Gentle Body Wash with Glycerine & Natural Oils - 500 ml",
    price: 349,
    product_type: "body care",
  },
  {
    department: "beauty & grooming",
    category: "bath,body & hygiene",
    img: "https://bit.ly/3AOXKC2",
    brand: "mCaffeine",
    name: "mCaffeine Naked & Raw Tan Removal Coffee Body Scrub - 100 gm",
    price: 425,
    product_type: "face care",
  },
  {
    department: "beauty & grooming",
    category: "bath,body & hygiene",
    img: "https://bit.ly/3CRxxDj",
    brand: "L'OCCITANE",
    name: "L'OCCITANE Savon Gourmand Almonds Delicious Soap 50 gm (Unisex)",
    price: 500,
    product_type: "Bar soap",
  },
  {
    department: "beauty & grooming",
    category: "fragrances & perfumes",
    img: "https://bit.ly/3kJxFyu",
    brand: "Titan",
    name: "Skinn by Titan Escapade Country Road Eau de Perfum for Men - 100 ml",
    price: 2395,
    product_type: "fragrances",
  },
  {
    department: "beauty & grooming",
    category: "fragrances & perfumes",
    img: "https://bit.ly/3EQAPZk",
    brand: "Studiowest",
    name: "Studiowest Ibiza Power by Westside Perfume Body Spray For Men - 100gm",
    price: 225,
    product_type: "fragrances",
  },
  {
    department: "beauty & grooming",
    category: "fragrances & perfumes",
    img: "https://bit.ly/3kJS5aL",
    brand: "Nautica",
    name: "Nautica Voyage Sport Eau de Toilette for Men - 100 ml",
    price: 2135,
    product_type: "fragrances",
  },
  {
    department: "beauty & grooming",
    category: "hair",
    img: "https://bit.ly/2Y5qE2C",
    brand: "Mamaearth",
    name: "Mamaearth Anti Hair Fall Spa Range with Onion Hair Oil + Onion Shampoo + Onion Conditioner - 550 ml",
    price: 1097,
    product_type: "shampoo & conditioner",
  },
  {
    department: "beauty & grooming",
    category: "hair",
    img: "https://bit.ly/3EWERiU",
    brand: "Biotique",
    name: "Biotique Bio Neem Margosa Anti - Dandruff Shampoo & Conditioner - 340 ml",
    price: 269,
    product_type: "shampoo & conditioner",
  },
  {
    department: "beauty & grooming",
    category: "hair",
    img: "https://bit.ly/3uiTtEq",
    brand: "Nat Habit",
    name: "Nat Habit Soybean Methi Summer Hair Oil Rough Dry Damage Repair - 200 ml",
    price: 509,
    product_type: "shampoo & conditioner",
  },
  {
    department: "beauty & grooming",
    category: "hair",
    img: "https://bit.ly/3zM7Ylo",
    brand: "Keratherapy",
    name: "Keratherapy Keratin Infused Moisture Shampoo - 300 ml",
    price: 1445,
    product_type: "shampoo & conditioner",
  },
  {
    department: "beauty & grooming",
    category: "hair",
    img: "https://bit.ly/3idwBkG",
    brand: "Wishcare",
    name: "Wishcare Argan Biotin Shampoo + Argan Vanilla Conditioner - 600 ml",
    price: 799,
    product_type: "shampoo & conditioner",
  },
  {
    department: "beauty & grooming",
    category: "makeup",
    img: "https://bit.ly/3zNeTKQ",
    //alt img: "https://bit.ly/3i9LIvC"
    brand: "Revlon",
    name: "Revlon 24HR Kajal Intense Black - 0.35 gm",
    price: 7,
    product_type: "eye",
  },
  {
    department: "beauty & grooming",
    category: "makeup",
    img: "https://bit.ly/3COVewb",
    //alt img: ""
    brand: "Faces Canada",
    name: "Faces Canada Ultimate Pro HD Mini Whopper Lashes Mascara 5 gm",
    price: 7,
    product_type: "eye",
  },
  {
    department: "beauty & grooming",
    category: "",
    img: "https://bit.ly/3ujTIz5",
    //alt img: ""
    brand: "Makeup Revolution",
    name: "Makeup Revolution Reloaded Combo III - 30 gm",
    price: 7,
    product_type: "eye",
  },
  {
    department: "beauty & grooming",
    category: "",
    img: "",
    //alt img: ""
    brand: "",
    name: "",
    price: 7,
    product_type: "",
  },
  {
    department: "beauty & grooming",
    category: "",
    img: "",
    //alt img: ""
    brand: "",
    name: "",
    price: 7,
    product_type: "",
  },
  {
    department: "beauty & grooming",
    category: "",
    img: "",
    //alt img: ""
    brand: "",
    name: "",
    price: 7,
    product_type: "",
  },
  {
    department: "beauty & grooming",
    category: "",
    img: "",
    //alt img: ""
    brand: "",
    name: "",
    price: 7,
    product_type: "",
  },
];
