let data = [
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3CPmtqo",
    brand: "Woodland",
    name: "Woodland Men's Rust Derby Shoes",
    price: "1497",
    product_type: "casual",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3kN8ISV",
    brand: "Woodland",
    name: "Woodland Men's Cashew Brown Derby Shoes",
    price: 1547,
    product_type: "casual",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3EYHD79",
    brand: "Woodland",
    name: "Woodland Men's Tan Floater Sandals",
    price: 1297,
    product_type: "sandals & floater",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3EZR6v2",
    brand: "Woodland",
    name: "Woodland Men's Black Boat Shoes",
    price: 1997,
    product_type: "casual",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/39KSwvg",
    brand: "Woodland",
    name: "Woodland Men's Brown Boat Shoes",
    price: 2297,
    product_type: "casual",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3ifYjxg",
    brand: "Woodland",
    name: "Woodland Men's Black Casual Boots",
    price: 2347,
    product_type: "boots",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3kLWJ83",
    brand: "Woodland",
    name: "Woodland Men's Brown Floater Sandals",
    price: 1297,
    product_type: "sandals & floater",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3m7s7NM",
    brand: "Woodland",
    name: "Woodland Men's Camel Outdoor Shoes",
    price: 1997,
    product_type: "sports shoes",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3CWt6r5",
    brand: "Woodland",
    name: "Woodland Men's Khaki Floater Sandals",
    price: 1297,
    product_type: "sandals & floater",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3oeCeDi",
    brand: "Woodland",
    name: "Woodland Men's Tan Boat Shoes",
    price: 2297,
    product_type: "casual",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3mmbZs7",
    brand: "Woodland",
    name: "Woodland Men's Khaki Outdoor Shoes",
    price: 1997,
    product_type: "sports shoes",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3CQhNAz",
    brand: "Woodland",
    name: "Woodland Men's Navy Casual Sneakers",
    price: 1747,
    product_type: "sneakers",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/39Fiss6",
    brand: "U.S. Polo Assn",
    name: "U.S. Polo Assn. Men's ATLAS2.0 Grey Casual Sneakers",
    price: 3219,
    product_type: "sneakers",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3uezDKw",
    brand: "U.S. Polo Assn",
    name: "U.S. Polo Assn. Men's XYLON2.0 Grey Casual Sneakers",
    price: 3599,
    product_type: "sneakers",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3zI7aO9",
    brand: "U.S. Polo Assn",
    name: "U.S. Polo Assn. Men's GAZETTE2.0 Off White Casual Sneakers",
    price: 3599,
    product_type: "sneakers",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/2XW00ZG",
    brand: "samsung",
    name: "Samsung Galaxy A03s 32 GB (Blue) 3 GB RAM, Dual SIM 4G",
    price: 11499,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3CQk4f5",
    brand: "nokia",
    name: "Nokia C20 Plus 32 GB (Blue) 3 GB RAM, Dual SIM 4G",
    price: 9970,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3zNzjUj",
    brand: "realme",
    name: "realme GT 128 GB (Dashing Blue) 8 GB RAM, Dual SIM 5G",
    price: 37999,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/2Wjrat1",
    brand: "vivo",
    name: "Vivo Y53s 128 GB (Fantastic Rainbow) 8 GB RAM, Dual SIM 4G",
    price: 19449,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3kMtMck",
    brand: "apple",
    name: "Apple iPhone 11 (64GB) - Green",
    price: 49900,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3ig2wky",
    brand: "realme",
    name: "realme GT Master Edition 256 GB (Voyager Grey) 8 GB RAM, Dual SIM 5G",
    price: 29996,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3EXGw84",
    brand: "vivo",
    name: "Vivo Y12G 32 GB (Phantom Black) 3 GB RAM, Dual SIM 4G",
    price: 10850,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/2ZCNy1L",
    brand: "oppo",
    name: "OPPO Reno 6 128 GB (Aurora) 8 GB RAM, Dual SIM 5G",
    price: 29980,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/2ZCNE9D",
    brand: "samsung",
    name: "Samsung Galaxy Z Flip3 256 GB (Cream) 8 GB RAM, Dual SIM 5G",
    price: 88999,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/39Gifoq",
    brand: "oneplus",
    name: "OnePlus 9 256 GB (Winter Mist) 12 GB RAM, Dual SIM 5G",
    price: 50990,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3CRXF0Z",
    brand: "xiaomi",
    name: "Xiaomi Redmi 9A 32 GB (Nature Green) 2 GB RAM, Dual SIM 4G",
    price: 7548,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/39IZ7X6",
    brand: "oneplus",
    name: "OnePlus 9R 128 GB (Lake Blue) 8 GB RAM, Dual SIM 5G",
    price: 39999,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "",
    brand: "",
    name: "",
    price: 3,
    product_type: "smartphones",
  },
  {
    department: "beauty & grooming",
    category: "bath,body & hygiene",
    img: "https://bit.ly/3EV3w7v",
    brand: "pears",
    name: "Pears Pure & Gentle Body Wash with Glycerine & Natural Oils - 500 ml",
    price: 349,
    product_type: "body care",
  },
  {
    department: "beauty & grooming",
    category: "bath,body & hygiene",
    img: "https://bit.ly/3AOXKC2",
    brand: "mCaffeine",
    name: "mCaffeine Naked & Raw Tan Removal Coffee Body Scrub - 100 gm",
    price: 425,
    product_type: "face care",
  },
  {
    department: "beauty & grooming",
    category: "bath,body & hygiene",
    img: "https://bit.ly/3CRxxDj",
    brand: "L'OCCITANE",
    name: "L'OCCITANE Savon Gourmand Almonds Delicious Soap 50 gm (Unisex)",
    price: 500,
    product_type: "Bar soap",
  },
  {
    department: "beauty & grooming",
    category: "fragrances & perfumes",
    img: "https://bit.ly/3kJxFyu",
    brand: "Titan",
    name: "Skinn by Titan Escapade Country Road Eau de Perfum for Men - 100 ml",
    price: 2395,
    product_type: "fragrances",
  },
  {
    department: "beauty & grooming",
    category: "fragrances & perfumes",
    img: "https://bit.ly/3EQAPZk",
    brand: "Studiowest",
    name: "Studiowest Ibiza Power by Westside Perfume Body Spray For Men - 100gm",
    price: 225,
    product_type: "fragrances",
  },
  {
    department: "beauty & grooming",
    category: "fragrances & perfumes",
    img: "https://bit.ly/3kJS5aL",
    brand: "Nautica",
    name: "Nautica Voyage Sport Eau de Toilette for Men - 100 ml",
    price: 2135,
    product_type: "fragrances",
  },
  {
    department: "beauty & grooming",
    category: "hair",
    img: "https://bit.ly/2Y5qE2C",
    brand: "Mamaearth",
    name: "Mamaearth Anti Hair Fall Spa Range with Onion Hair Oil + Onion Shampoo + Onion Conditioner - 550 ml",
    price: 1097,
    product_type: "shampoo & conditioner",
  },
  {
    department: "beauty & grooming",
    category: "hair",
    img: "https://bit.ly/3EWERiU",
    brand: "Biotique",
    name: "Biotique Bio Neem Margosa Anti - Dandruff Shampoo & Conditioner - 340 ml",
    price: 269,
    product_type: "shampoo & conditioner",
  },
  {
    department: "beauty & grooming",
    category: "hair",
    img: "https://bit.ly/3uiTtEq",
    brand: "Nat Habit",
    name: "Nat Habit Soybean Methi Summer Hair Oil Rough Dry Damage Repair - 200 ml",
    price: 509,
    product_type: "shampoo & conditioner",
  },
  {
    department: "beauty & grooming",
    category: "hair",
    img: "https://bit.ly/3zM7Ylo",
    brand: "Keratherapy",
    name: "Keratherapy Keratin Infused Moisture Shampoo - 300 ml",
    price: 1445,
    product_type: "shampoo & conditioner",
  },
  {
    department: "beauty & grooming",
    category: "hair",
    img: "https://bit.ly/3idwBkG",
    brand: "Wishcare",
    name: "Wishcare Argan Biotin Shampoo + Argan Vanilla Conditioner - 600 ml",
    price: 799,
    product_type: "shampoo & conditioner",
  },
  {
    department: "beauty & grooming",
    category: "makeup",
    img: "https://bit.ly/3zNeTKQ",
    //alt img: "https://bit.ly/3i9LIvC"
    brand: "Revlon",
    name: "Revlon 24HR Kajal Intense Black - 0.35 gm",
    price: 449,
    product_type: "eye",
  },
  {
    department: "beauty & grooming",
    category: "makeup",
    img: "https://bit.ly/3COVewb",
    //alt img: ""
    brand: "Faces Canada",
    name: "Faces Canada Ultimate Pro HD Mini Whopper Lashes Mascara 5 gm",
    price: 659,
    product_type: "eye",
  },
  {
    department: "beauty & grooming",
    category: "",
    img: "https://bit.ly/3ujTIz5",
    //alt img: ""
    brand: "Makeup Revolution",
    name: "Makeup Revolution Reloaded Combo III - 30 gm",
    price: 1050,
    product_type: "eye",
  },
];
