let shoesData = [
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3CPmtqo",
    brand: "Woodland",
    name: "Woodland Men's Rust Derby Shoes",
    price: "1497",
    product_type: "casual",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3kN8ISV",
    brand: "Woodland",
    name: "Woodland Men's Cashew Brown Derby Shoes",
    price: 1547,
    product_type: "casual",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3EYHD79",
    brand: "Woodland",
    name: "Woodland Men's Tan Floater Sandals",
    price: 1297,
    product_type: "sandals & floater",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3EZR6v2",
    brand: "Woodland",
    name: "Woodland Men's Black Boat Shoes",
    price: 1997,
    product_type: "casual",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/39KSwvg",
    brand: "Woodland",
    name: "Woodland Men's Brown Boat Shoes",
    price: 2297,
    product_type: "casual",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3ifYjxg",
    brand: "Woodland",
    name: "Woodland Men's Black Casual Boots",
    price: 2347,
    product_type: "boots",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3kLWJ83",
    brand: "Woodland",
    name: "Woodland Men's Brown Floater Sandals",
    price: 1297,
    product_type: "sandals & floater",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3m7s7NM",
    brand: "Woodland",
    name: "Woodland Men's Camel Outdoor Shoes",
    price: 1997,
    product_type: "sports shoes",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3CWt6r5",
    brand: "Woodland",
    name: "Woodland Men's Khaki Floater Sandals",
    price: 1297,
    product_type: "sandals & floater",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3oeCeDi",
    brand: "Woodland",
    name: "Woodland Men's Tan Boat Shoes",
    price: 2297,
    product_type: "casual",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3mmbZs7",
    brand: "Woodland",
    name: "Woodland Men's Khaki Outdoor Shoes",
    price: 1997,
    product_type: "sports shoes",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3CQhNAz",
    brand: "Woodland",
    name: "Woodland Men's Navy Casual Sneakers",
    price: 1747,
    product_type: "sneakers",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/39Fiss6",
    brand: "U.S. Polo Assn",
    name: "U.S. Polo Assn. Men's ATLAS2.0 Grey Casual Sneakers",
    price: 3219,
    product_type: "sneakers",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3uezDKw",
    brand: "U.S. Polo Assn",
    name: "U.S. Polo Assn. Men's XYLON2.0 Grey Casual Sneakers",
    price: 3599,
    product_type: "sneakers",
  },
  {
    department: "footwear",
    category: "men",
    img: "https://bit.ly/3zI7aO9",
    brand: "U.S. Polo Assn",
    name: "U.S. Polo Assn. Men's GAZETTE2.0 Off White Casual Sneakers",
    price: 3599,
    product_type: "sneakers",
  },
];
