let smartphoesData = [
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/2XW00ZG",
    brand: "samsung",
    name: "Samsung Galaxy A03s 32 GB (Blue) 3 GB RAM, Dual SIM 4G",
    price: 11499,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3CQk4f5",
    brand: "nokia",
    name: "Nokia C20 Plus 32 GB (Blue) 3 GB RAM, Dual SIM 4G",
    price: 9970,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3zNzjUj",
    brand: "realme",
    name: "realme GT 128 GB (Dashing Blue) 8 GB RAM, Dual SIM 5G",
    price: 37999,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/2Wjrat1",
    brand: "vivo",
    name: "Vivo Y53s 128 GB (Fantastic Rainbow) 8 GB RAM, Dual SIM 4G",
    price: 19449,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3kMtMck",
    brand: "apple",
    name: "Apple iPhone 11 (64GB) - Green",
    price: 49900,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3ig2wky",
    brand: "realme",
    name: "realme GT Master Edition 256 GB (Voyager Grey) 8 GB RAM, Dual SIM 5G",
    price: 29996,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3EXGw84",
    brand: "vivo",
    name: "Vivo Y12G 32 GB (Phantom Black) 3 GB RAM, Dual SIM 4G",
    price: 10850,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/2ZCNy1L",
    brand: "oppo",
    name: "OPPO Reno 6 128 GB (Aurora) 8 GB RAM, Dual SIM 5G",
    price: 29980,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/2ZCNE9D",
    brand: "samsung",
    name: "Samsung Galaxy Z Flip3 256 GB (Cream) 8 GB RAM, Dual SIM 5G",
    price: 88999,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/39Gifoq",
    brand: "oneplus",
    name: "OnePlus 9 256 GB (Winter Mist) 12 GB RAM, Dual SIM 5G",
    price: 50990,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/3CRXF0Z",
    brand: "xiaomi",
    name: "Xiaomi Redmi 9A 32 GB (Nature Green) 2 GB RAM, Dual SIM 4G",
    price: 7548,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "https://bit.ly/39IZ7X6",
    brand: "oneplus",
    name: "OnePlus 9R 128 GB (Lake Blue) 8 GB RAM, Dual SIM 5G",
    price: 39999,
    product_type: "smartphones",
  },
  {
    department: "electronics",
    category: "mobile phones",
    img: "",
    brand: "",
    name: "",
    price: 3,
    product_type: "smartphones",
  },
];
